spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: vuhso04
    password: 123abc
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
        ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            format_sql: true
app:
  auth:
    tokenExpiration: 120000
    refreshTokenExpiration: 86400000
server:
  port: 8082


